title = "Stock Predictor using ML and DS - REVA University - B.Tech CSE - Group H1 - Batch of 2020"
ticker_MSFTDESC = "Microsoft Corporation"
ticker_DISDESC = "The Walt Disney Company"
ticker_BADESC = "The Boeing Company"
ticker_INTCDESC = "Intel Corporation"